#!/usr/bin/env bash
# scripts/extract_core_meta.sh — regenerate src/lang/clj/clojure/core_meta.clj
# (D-305): :arglists/:doc for clojure.core vars, extracted from the JVM oracle
# and filtered to the vars cljw actually interns. Run on demand after the core
# surface grows; needs `clj` + a built zig-out/bin/cljw.
set -euo pipefail
cd "$(dirname "$0")/.."
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# 1. JVM oracle: every public var's [qualified-sym arglists doc] across the
# EAGER-bundled namespaces (a lazy ns's vars are not interned when the eager
# core_meta.clj runs, so its rows would be dead weight — extend alongside a
# lazy-region post-load hook if that lands).
timeout 60 clj -J-Xmx2g -M -e '
(doseq [ns-sym (quote [clojure.core clojure.string clojure.walk clojure.edn
                       clojure.core.protocols clojure.java.io])]
  (require ns-sym)
  (doseq [[sym v] (sort-by key (ns-publics ns-sym))]
    (let [m (meta v)]
      (when (or (:arglists m) (:doc m))
        (prn [(symbol (name ns-sym) (name sym)) (:arglists m) (:doc m)])))))' > "$TMP/raw.edn"

# 2. cljw truth: the interned public core vars.
./zig-out/bin/cljw -e '(do (require (quote clojure.string) (quote clojure.walk) (quote clojure.edn) (quote clojure.core.protocols) (quote clojure.java.io)) (doseq [n [(quote clojure.core) (quote clojure.string) (quote clojure.walk) (quote clojure.edn) (quote clojure.core.protocols) (quote clojure.java.io)] [s _] (ns-publics n)] (println (str n "/" (name s)))))' > "$TMP/cljw_vars.txt"

# 3. Intersect + emit.
timeout 60 clj -J-Xmx2g -M -e "
(require '[clojure.edn :as edn] '[clojure.java.io :as io] '[clojure.string :as str])
(let [cljw-vars (-> (slurp \"$TMP/cljw_vars.txt\") str/split-lines set)
      rows (->> (line-seq (io/reader \"$TMP/raw.edn\"))
                (map edn/read-string)
                (filter (fn [[s _ _]] (contains? cljw-vars (str s)))))]
  (println \";; SPDX-License-Identifier: EPL-2.0\")
  (println \";;\")
  (println \";;   Copyright (c) Rich Hickey. All rights reserved.\")
  (println \";;   The use and distribution terms for this software are covered by the\")
  (println \";;   Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php).\")
  (println \";;   By using this software in any fashion, you are agreeing to be bound by the\")
  (println \";;   terms of this license. You must not remove this notice, or any other, from\")
  (println \";;   this software.\")
  (println \";;\")
  (println \";;   core_meta.clj — :arglists/:doc for clojure.core vars; docstring text\")
  (println \";;   reproduced verbatim from Clojure's core sources. Reproduced in\")
  (println \";;   ClojureWasm; redistributed under EPL-2.0 per EPL-1.0 §7. ClojureWasm\")
  (println \";;   changes (c) the ClojureWasm authors.\")
  (println \";;   GENERATED by scripts/extract_core_meta.sh — do not hand-edit.\")
  (println)
  (println \"(ns clojure.core-meta)\")
  (println)
  (println \";; Existing keys win: a var's own meta (a defn-attached :arglists) is\")
  (println \";; preserved; only the missing keys are filled from the oracle table.\")
  (println \"(def ^:private fill (fn [m mm] (merge mm m)))\")
  (println)
  (doseq [[s args doc] rows]
    (let [mm (cond-> {}
               args (assoc :arglists (list 'quote args))
               doc (assoc :doc doc))]
      ;; (resolve 'sym), NOT (var sym): a Var VALUE in the literal pool is
      ;; not bytecode-serializable (AOT cache_gen), a quoted symbol is.
      ;; when-let guards a var a build variant might not intern.
      (prn (list 'when-let ['v (list 'resolve (list 'quote s))] (list 'alter-meta! 'v 'fill mm)))))
  (println)
  (println \";; generated:\" (count rows) \"vars\"))" > src/lang/clj/clojure/core_meta.clj
tail -1 src/lang/clj/clojure/core_meta.clj
